### ISSUE TITLE
Displaying skeleton of the recognized keypoints

### ISSUE THREAD

**Issue by xprilion** [monilchheda/manning-live-project-human-pose-estimation#1]
Hey @monilchheda, great work with the submission! I can see you did quite some exploration of your own while doing it which is amazing!

One small change I'd request is to add code to display the skeleton over both the uncropped and cropped images (separately from the labels or with them, is up to you) and then I guess we can call this submission complete :) Good luck!

**Comment by monilchheda** [comment]
@xprilion Its all set. Please review.

**Comment by xprilion** [comment]
This is great! Thanks for addressing the issue, I'll go ahead and mark it closed. Congratulations on completing the first-week task! Good luck with the next one, I find it very testing for me! :smiley:
